// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 NorseHorse

// KeyAlgorithm.swift
// PGPonyCore
//
// The set of OpenPGP key algorithms PGPony understands, plus the mapping from
// OpenPGP algorithm IDs (v4 RFC 4880 / v6 RFC 9580) to those cases. This is a
// Foundation-only value type: no SwiftData, no UI. KeyServer.mayNotAccept(_:)
// and callers reason over these cases.
//
// String(localized:) is used for display names so a host app's string catalog
// can localize them; in the standalone core (no catalog) it simply returns the
// key, which is fine — these are protocol-level identifiers.

import Foundation

enum KeyAlgorithm: String, Codable, CaseIterable {
    case rsa2048 = "RSA 2048"
    case rsa4096 = "RSA 4096"
    case ed25519 = "Ed25519+Cv25519"
    // RFC 9580 v6 algorithm variants (import only — not generated by PGPony yet)
    case v6Ed25519 = "Ed25519 (v6)"
    case v6X25519 = "X25519 (v6)"
    case v6Ed448 = "Ed448 (v6)"
    case v6X448 = "X448 (v6)"
    case v6MLKEM768 = "ML-KEM-768+X25519 (v6)"
    case librePGPKyber = "ML-KEM-768+X25519 (LibrePGP)"

    var displayName: String {
        switch self {
        case .rsa2048:   return String(localized: "RSA 2048")
        case .rsa4096:   return String(localized: "RSA 4096")
        case .ed25519:   return String(localized: "Ed25519+Cv25519")
        case .v6Ed25519: return String(localized: "Ed25519 (v6)")
        case .v6X25519:  return String(localized: "X25519 (v6)")
        case .v6Ed448:   return String(localized: "Ed448 (v6)")
        case .v6X448:    return String(localized: "X448 (v6)")
        case .v6MLKEM768:    return String(localized: "Ed25519 + ML-KEM-768 (v6, post-quantum)")
        case .librePGPKyber: return String(localized: "Ed25519 + ML-KEM-768 (LibrePGP, post-quantum)")
        }
    }

    var shortName: String {
        switch self {
        case .rsa2048: return "RSA-2048"
        case .rsa4096: return "RSA-4096"
        case .ed25519: return "Ed25519"
        case .v6Ed25519: return "Ed25519 v6"
        case .v6X25519: return "X25519 v6"
        case .v6Ed448: return "Ed448 v6"
        case .v6X448: return "X448 v6"
        case .v6MLKEM768: return "ML-KEM-768 v6"
        case .librePGPKyber: return "ML-KEM-768 LibrePGP"
        }
    }

    var keyBits: Int {
        switch self {
        case .rsa2048: return 2048
        case .rsa4096: return 4096
        case .ed25519, .v6Ed25519, .v6X25519, .v6MLKEM768, .librePGPKyber: return 256
        case .v6Ed448, .v6X448: return 448
        }
    }

    /// Whether this is an RFC 9580 v6 key type
    var isV6: Bool {
        switch self {
        case .v6Ed25519, .v6X25519, .v6Ed448, .v6X448: return true
        default: return false
        }
    }

    /// Whether this algorithm is post-quantum (composite ML-KEM-768 + X25519).
    var isPostQuantum: Bool {
        switch self {
        case .v6MLKEM768, .librePGPKyber: return true
        default: return false
        }
    }

    /// Whether this algorithm uses native Curve25519 for encryption (ECDH subkey).
    var usesCv25519: Bool {
        switch self {
        case .ed25519, .v6Ed25519, .v6X25519: return true
        default: return false
        }
    }

    var isRSA: Bool {
        switch self {
        case .rsa2048, .rsa4096: return true
        default: return false
        }
    }

    /// Algorithms that can be selected in the key generation UI.
    static var generatable: [KeyAlgorithm] {
        [.rsa2048, .rsa4096, .ed25519, .v6Ed25519, .v6MLKEM768, .librePGPKyber]
    }

    /// Map an OpenPGP algorithm ID + key version to a KeyAlgorithm.
    /// Handles both v4 (RFC 4880) and v6 (RFC 9580) algorithm IDs.
    static func from(algorithmID: UInt8, keyVersion: UInt8 = 4) -> KeyAlgorithm? {
        if keyVersion == 6 {
            switch algorithmID {
            case 27:        return .v6Ed25519   // Ed25519 signing key
            case 25:        return .v6X25519    // X25519 encryption subkey
            case 35:        return .v6MLKEM768  // ML-KEM-768 + X25519 composite (RFC 9980)
            case 28:        return .v6Ed448     // Ed448 signing key
            case 26:        return .v6X448      // X448 encryption subkey
            case 1, 2, 3:   return .rsa4096     // RSA (bit size not derivable from algo ID)
            case 22:        return .ed25519     // Legacy EdDSA OID
            case 18:        return .ed25519     // Legacy ECDH
            default:        return nil
            }
        } else {
            switch algorithmID {
            case 1, 2, 3:   return .rsa4096     // RSA — bit size not derivable from algo ID
            case 22:        return .ed25519     // EdDSA (legacy OID-based Ed25519)
            case 18:        return .ed25519     // ECDH (Cv25519 subkey)
            default:        return nil
            }
        }
    }
}
