// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 NorseHorse

// KeyAlgorithm.swift
// PGPonyCore
//
// The set of OpenPGP key algorithms PGPony understands, plus the mapping from
// OpenPGP algorithm IDs (v4 RFC 4880 / v6 RFC 9580) to those cases. This is a
// Foundation-only value type: no SwiftData, no UI. KeyServer.mayNotAccept(_:)
// and callers reason over these cases.
//
// CORE SEAM: in the app this enum lives alongside the SwiftData models in
// PGPKeyModel.swift; the core lifts it out on its own so nothing here depends
// on SwiftData. Curve recognition comes from ECCurveOID.swift, lifted the same
// way.
//
// String(localized:) is used for display names so a host app's string catalog
// can localize them; in the standalone core (no catalog) it simply returns the
// key, which is fine — these are protocol-level identifiers.

import Foundation

enum KeyAlgorithm: String, Codable, CaseIterable {
    case rsa2048 = "RSA 2048"
    case rsa4096 = "RSA 4096"
    // 8.3.0 (Android 4.4.1 parity): RSA sizes read off the modulus, so an
    // imported 3072 or 8192 key stops being labeled 4096. Import only.
    case rsa3072 = "RSA 3072"
    case rsa8192 = "RSA 8192"
    case ed25519 = "Ed25519+Cv25519"
    // RFC 9580 v6 algorithm variants (import only — not generated by PGPony yet)
    case v6Ed25519 = "Ed25519 (v6)"
    case v6X25519 = "X25519 (v6)"
    case v6Ed448 = "Ed448 (v6)"
    case v6X448 = "X448 (v6)"
    case v6MLKEM768 = "ML-KEM-768+X25519 (v6)"
    // v8.2.0 §1: the 1024 composite suite (RFC 9980 algorithm 36).
    case v6MLKEM1024 = "ML-KEM-1024+X448 (v6)"
    // 8.3.0 (planning 4.1, Android 4.4.0): RFC 9980 composite SIGNATURE
    // primaries (algorithms 30 and 31). The whole key is post-quantum: an
    // ML-DSA + EdDSA primary that certifies and signs, with an ML-KEM
    // composite encryption subkey. 65 is generated (iOS 26 provides ML-DSA);
    // 87 imports and labels only, its Ed448 half having no implementation here.
    case v6MLDSA65 = "ML-DSA-65+Ed25519 (v6)"
    case v6MLDSA87 = "ML-DSA-87+Ed448 (v6)"
    // 8.3.0 (planning 4.3, Android 4.5.0 item 14): the v4 interop shape. A
    // v4 Ed25519 primary with a Cv25519 subkey for classical correspondents
    // and an RFC 9980 algorithm 35 ML-KEM-768 + X25519 encryption subkey, the
    // one post-quantum method RFC 9980 allows on a v4 key. Maximum reach:
    // classical tools use the Cv25519 subkey, PQ-capable ones the ML-KEM one.
    case v4MLKEM768 = "ML-KEM-768+X25519 (v4)"
    case librePGPKyber = "ML-KEM-768+X25519 (LibrePGP)"
    // v8.2.0 §1 (K2a): the LibrePGP 1024 form (gpg ky1024_cv448, still algo 8).
    case librePGPKyber1024 = "ML-KEM-1024+X448 (LibrePGP)"
    // 8.3.0 (NIST A to E): the NIST prime curves are usable (ECDSA sign and
    // verify, ECDH encrypt and decrypt, all on CryptoKit), one label each.
    case nistP256 = "NIST P-256"
    case nistP384 = "NIST P-384"
    case nistP521 = "NIST P-521"
    // v8.2.0 issue #2: recognition only. GnuPG/GPG4WIN keys on brainpool
    // curves import with a real label instead of being mislabeled as RSA;
    // PGPony does not sign/encrypt with them (CryptoKit has no brainpool).
    case otherEC = "EC key"
    
    // v5.0 Phase 5.1 — wrap each case in String(localized:) so Text(algorithm
    // .displayName) localizes via Localizable.xcstrings. Crypto identifiers
    // (RSA 2048, Ed25519+Cv25519, etc.) are kept verbatim in every language
    // since they're protocol-level names, but going through the catalog keeps
    // the lookup path uniform with the rest of the enums.
    var displayName: String {
        switch self {
        case .rsa2048:   return String(localized: "RSA 2048")
        case .rsa4096:   return String(localized: "RSA 4096")
        case .rsa3072:   return String(localized: "RSA 3072")
        case .rsa8192:   return String(localized: "RSA 8192")
        case .ed25519:   return String(localized: "Ed25519+Cv25519")
        case .v6Ed25519: return String(localized: "Ed25519 (v6)")
        case .v6X25519:  return String(localized: "X25519 (v6)")
        case .v6Ed448:   return String(localized: "Ed448 (v6)")
        case .v6X448:    return String(localized: "X448 (v6)")
        case .v6MLKEM768:    return String(localized: "Ed25519 + ML-KEM-768 (v6, post-quantum)")
        case .v6MLKEM1024:   return String(localized: "Ed25519 + ML-KEM-1024 (v6, post-quantum)")
        case .librePGPKyber: return String(localized: "Ed25519 + ML-KEM-768 (LibrePGP, post-quantum)")
        case .librePGPKyber1024: return String(localized: "Ed25519 + ML-KEM-1024 (LibrePGP, post-quantum)")
        case .v4MLKEM768:    return String(localized: "Ed25519 + ML-KEM-768 (v4, post-quantum)")
        case .v6MLDSA65: return String(localized: "ML-DSA-65 + Ed25519 (v6, post-quantum signatures)")
        case .v6MLDSA87: return String(localized: "ML-DSA-87 + Ed448 (v6, post-quantum signatures)")
        case .nistP256: return String(localized: "NIST P-256 (ECDSA + ECDH)")
        case .nistP384: return String(localized: "NIST P-384 (ECDSA + ECDH)")
        case .nistP521: return String(localized: "NIST P-521 (ECDSA + ECDH)")
        case .otherEC: return String(localized: "EC key (brainpool, recognition only)")
        }
    }

    var shortName: String {
        switch self {
        case .rsa2048: return "RSA-2048"
        case .rsa4096: return "RSA-4096"
        case .rsa3072: return "RSA-3072"
        case .rsa8192: return "RSA-8192"
        case .ed25519: return "Ed25519"
        case .v6Ed25519: return "Ed25519 v6"
        case .v6X25519: return "X25519 v6"
        case .v6Ed448: return "Ed448 v6"
        case .v6X448: return "X448 v6"
        case .v6MLKEM768: return "ML-KEM-768 v6"
        case .v6MLKEM1024: return "ML-KEM-1024 v6"
        case .librePGPKyber: return "ML-KEM-768 LibrePGP"
        case .librePGPKyber1024: return "ML-KEM-1024 LibrePGP"
        case .v4MLKEM768: return "ML-KEM-768 v4"
        case .v6MLDSA65: return "ML-DSA-65 v6"
        case .v6MLDSA87: return "ML-DSA-87 v6"
        case .nistP256: return "P-256"
        case .nistP384: return "P-384"
        case .nistP521: return "P-521"
        case .otherEC: return "EC"
        }
    }
    
    var keyBits: Int {
        switch self {
        case .rsa2048: return 2048
        case .rsa4096: return 4096
        case .rsa3072: return 3072
        case .rsa8192: return 8192
        case .ed25519, .v6Ed25519, .v6X25519, .v6MLKEM768, .librePGPKyber, .v6MLDSA65, .v4MLKEM768: return 256
        // The 1024 composites' classical half is X448, so they group with the
        // 448-bit curves for display purposes.
        case .v6Ed448, .v6X448, .v6MLKEM1024, .librePGPKyber1024, .v6MLDSA87: return 448
        case .nistP256: return 256
        case .nistP384: return 384
        case .nistP521: return 521
        case .otherEC: return 0   // curve not tracked; recognition only
        }
    }

    /// Whether this is an RFC 9580 v6 key type.
    ///
    /// v8.2.1 — the ML-KEM composites (RFC 9980 algorithms 35/36) are v6 keys:
    /// their fingerprints are 32-octet SHA-256 (key ID at the leading end) and
    /// their format is RFC 9580, not RFC 4880. Leaving them out made the key
    /// detail screen label a post-quantum key "OpenPGP v4 · RFC 4880" and made
    /// the model's longKeyID/shortKeyID take the trailing bytes (v4) instead of
    /// the leading bytes (v6). The LibrePGP composites stay out: they are the
    /// GnuPG (algorithm 8) form, not RFC 9580 v6.
    var isV6: Bool {
        switch self {
        case .v6Ed25519, .v6X25519, .v6Ed448, .v6X448, .v6MLKEM768, .v6MLKEM1024, .v6MLDSA65, .v6MLDSA87: return true
        default: return false
        }
    }

    /// Whether this algorithm is post-quantum (a composite ML-KEM suite, or a
    /// composite ML-DSA signature primary, which always carries one).
    var isPostQuantum: Bool {
        switch self {
        case .v6MLKEM768, .v6MLKEM1024, .librePGPKyber, .librePGPKyber1024, .v6MLDSA65, .v6MLDSA87, .v4MLKEM768: return true
        default: return false
        }
    }

    /// 8.3.0 (4.1): an RFC 9980 composite SIGNATURE primary (algorithm 30 or
    /// 31). Such a key signs and certifies with its ML-DSA + EdDSA primary
    /// rather than with an Ed25519 component.
    var isCompositeSignature: Bool {
        switch self {
        case .v6MLDSA65, .v6MLDSA87: return true
        default: return false
        }
    }

    /// 8.3.0 (4.1): a v6 key PAIR shape this app manages in full through the
    /// v6 builders (V6KeyGenerator): expiration edits, subkeys, user IDs. The
    /// model's algorithm names the whole suite, so the ML-KEM composites read
    /// as v6 here even though their label is the subkey's. Replaces the
    /// `== .v6Ed25519 || == .v6MLKEM768 || == .v6MLKEM1024` chains.
    var isV6Suite: Bool {
        switch self {
        case .v6Ed25519, .v6MLKEM768, .v6MLKEM1024, .v6MLDSA65, .v6MLDSA87: return true
        default: return false
        }
    }

    /// Whether this is a LibrePGP (GnuPG, algorithm 8) composite, either
    /// level. The message-decrypt router keys its LibrePGP path off this.
    ///
    /// v8.2.0 §1: deliberately EXHAUSTIVE (no `default`). The router used to
    /// enumerate the LibrePGP cases inline in a boolean filter, and when the
    /// 1024 variant was added the filter silently dropped it (a key that
    /// decrypted fine in isolation reported "no matching key" in the app,
    /// caught only on device). Routing through this property, whose switch
    /// forces every future KeyAlgorithm to declare itself LibrePGP-or-not,
    /// keeps that class of bug from recurring. Locked by
    /// KeyAlgorithmTests.testIsLibrePGPCoversBothSuitesOnly.
    var isLibrePGP: Bool {
        switch self {
        case .librePGPKyber, .librePGPKyber1024:
            return true
        case .rsa2048, .rsa3072, .rsa4096, .rsa8192, .ed25519, .v6Ed25519, .v6X25519, .v6Ed448,
             .v6X448, .v6MLKEM768, .v6MLKEM1024, .v6MLDSA65, .v6MLDSA87, .v4MLKEM768,
             .nistP256, .nistP384, .nistP521, .otherEC:
            return false
        }
    }

    /// Whether this algorithm uses native Curve25519 for encryption (ECDH subkey)
    /// Used for routing encrypt/decrypt to the native Cv25519 path vs ObjectivePGP.
    var usesCv25519: Bool {
        switch self {
        case .ed25519, .v6Ed25519, .v6X25519: return true
        default: return false
        }
    }

    var isRSA: Bool {
        switch self {
        case .rsa2048, .rsa3072, .rsa4096, .rsa8192: return true
        default: return false
        }
    }

    /// 8.3.0 (NIST A to E): a key on one of the NIST prime curves, which
    /// this app signs, verifies, encrypts to and decrypts with on CryptoKit.
    var isNIST: Bool {
        switch self {
        case .nistP256, .nistP384, .nistP521: return true
        default: return false
        }
    }

    var nistCurve: NISTCurve? {
        switch self {
        case .nistP256: return .p256
        case .nistP384: return .p384
        case .nistP521: return .p521
        default: return nil
        }
    }

    /// Algorithms that can be selected in the key generation UI.
    /// v5.0 Phase 2b: v6Ed25519 generation deferred to v6.0 release.
    /// V6KeyGenerator.swift remains in the codebase as groundwork for v6.0,
    /// where v6 gen will be paired with hardware-key support and properly
    /// validated against RFC 9580 Appendix A test vectors.
    /// All v6 variants (v6Ed25519, v6X25519, v6Ed448, v6X448) remain import-only.
    /// v6 Ed25519 generation is enabled (RFC 9580; produces a cert-only primary
    /// with Ed25519 signing + X25519 encryption subkeys, validated against sq).
    /// The other v6 variants (v6X25519-primary, v6Ed448, v6X448) remain
    /// import-only.
    static var generatable: [KeyAlgorithm] { generatableGroups.flatMap { $0.algorithms } }

    /// 8.3.0 (planning 4.2): the keygen choice organized by interop tier, in
    /// Android's order. Classical keys; the three RFC 9980 post-quantum
    /// shapes (v4 interop with the widest reach, the v6 ML-KEM composites,
    /// and the all-post-quantum ML-DSA primary); and the GnuPG LibrePGP
    /// forms, which only GnuPG and PGPony read. `generatable` is the flat
    /// view of the same list, so the two can never disagree.
    struct GeneratableGroup: Identifiable {
        let title: String
        let algorithms: [KeyAlgorithm]
        var id: String { title }
    }

    static var generatableGroups: [GeneratableGroup] {
        // 8.3.0 (4.1): the composite signature suite needs the OS's ML-DSA
        // (CryptoKit, iOS 26); on an earlier OS the picker leaves it out and
        // GenerateKeyView says why.
        var postQuantum: [KeyAlgorithm] = [.v4MLKEM768, .v6MLKEM768, .v6MLKEM1024]
        if MLDSAService.isAvailable { postQuantum.append(.v6MLDSA65) }
        return [
            GeneratableGroup(title: String(localized: "Classical"),
                             algorithms: [.rsa2048, .rsa4096, .ed25519, .v6Ed25519]),
            GeneratableGroup(title: String(localized: "Post-quantum (RFC 9980)"),
                             algorithms: postQuantum),
            GeneratableGroup(title: String(localized: "GnuPG / LibrePGP compatibility"),
                             algorithms: [.librePGPKyber, .librePGPKyber1024]),
        ]
    }

    /// Map an OpenPGP algorithm ID + key version to a KeyAlgorithm.
    /// Handles both v4 (RFC 4880) and v6 (RFC 9580) algorithm IDs.
    ///
    /// - Parameters:
    ///   - algorithmID: OpenPGP algorithm byte from the key packet
    ///   - keyVersion: Key packet version (4 or 6)
    /// - Returns: Matching KeyAlgorithm, or nil for unknown combinations
    static func from(algorithmID: UInt8, keyVersion: UInt8 = 4) -> KeyAlgorithm? {
        if keyVersion == 6 {
            switch algorithmID {
            case 27:        return .v6Ed25519   // Ed25519 signing key
            case 25:        return .v6X25519    // X25519 encryption subkey
            case 35:        return .v6MLKEM768  // ML-KEM-768 + X25519 composite (RFC 9980)
            case 36:        return .v6MLKEM1024 // ML-KEM-1024 + X448 composite (RFC 9980)
            case 30:        return .v6MLDSA65   // ML-DSA-65 + Ed25519 composite signature (RFC 9980)
            case 31:        return .v6MLDSA87   // ML-DSA-87 + Ed448 composite signature (RFC 9980)
            case 28:        return .v6Ed448     // Ed448 signing key
            case 26:        return .v6X448      // X448 encryption subkey
            // v6 can also carry legacy algorithm IDs (RSA, ECDH, etc.)
            case 1, 2, 3:   return .rsa4096     // RSA (we can't tell bit size from algo ID alone)
            case 22:        return .ed25519     // Legacy EdDSA OID — unlikely in v6 but valid
            case 18:        return .ed25519     // Legacy ECDH — unlikely in v6 but valid
            default:        return nil
            }
        } else {
            // V4 (RFC 4880)
            switch algorithmID {
            case 1, 2, 3:   return .rsa4096     // RSA — can't tell bit size from algo ID alone
            case 22:        return .ed25519     // EdDSA (legacy OID-based Ed25519)
            case 18:        return .ed25519     // ECDH (Cv25519 subkey)
            case 35:        return .v4MLKEM768  // ML-KEM-768 + X25519 on a v4 subkey (RFC 9980 3.5; 8.3.0, 4.3)
            default:        return nil
            }
        }
    }

    /// Recognize a key's algorithm from its full v4/v6 key-packet body. brainpool
    /// and NIST EC keys (which PGPony does not itself use) map to `.otherEC` so
    /// they import with a real label instead of falling back to RSA (algo 19 ->
    /// nil) or being mislabeled as Cv25519 (algo 18). Everything else delegates
    /// to `from(algorithmID:keyVersion:)`.
    static func from(keyPacketBody body: [UInt8]) -> KeyAlgorithm? {
        guard body.count > 6 else { return nil }
        let version = body[0]
        if version == 4, let curve = ECCurve.fromKeyPacketBody(body) {
            // 8.3.0 (NIST E): a NIST curve names its own case; the rest of the
            // recognition-only family (brainpool) stays the generic EC label.
            if let nist = curve.nistCurve { return nist.keyAlgorithm }
            if curve.isRecognitionOnly { return .otherEC }
        }
        let algo = body[5]
        if algo == 1 || algo == 2 || algo == 3, let bits = rsaModulusBits(keyPacketBody: body) {
            return rsaSize(forModulusBits: bits)
        }
        return from(algorithmID: algo, keyVersion: version)
    }

    /// Bit length of the RSA modulus MPI in a v4 or v6 key packet body, or
    /// nil when the body is not RSA or too short. v4: the MPI starts right
    /// after the algorithm octet; v6 carries a 4-octet key-material length
    /// first (RFC 9580 5.5.2).
    static func rsaModulusBits(keyPacketBody body: [UInt8]) -> Int? {
        guard body.count > 6, [1, 2, 3].contains(body[5]) else { return nil }
        let off = body[0] == 6 ? 10 : 6
        guard body.count >= off + 2 else { return nil }
        return Int(body[off]) << 8 | Int(body[off + 1])
    }

    /// The label for an RSA key of `bits`, rounded up to the next size PGPony
    /// names (a 3000-bit modulus reads as 3072, an odd 5000-bit one as 8192).
    static func rsaSize(forModulusBits bits: Int) -> KeyAlgorithm {
        switch bits {
        case ...2048: return .rsa2048
        case ...3072: return .rsa3072
        case ...4096: return .rsa4096
        default:      return .rsa8192
        }
    }
}
